export const styles = {
  adminPanelCont: {
    width: '560px',
    display: 'flex',
    flexDirection: 'row-reverse' as 'row-reverse',
  },
  valueContainer: {
    display: 'flex',
    flexDirection: 'row' as 'row',
    alignItems: 'center',
    gap: '10px',
  },
  container: {
    display: 'flex',
    padding: '20px',
    alignItems: 'center',
    flexDirection: 'column' as 'column',
    gap: 20,
  },
  card: {
    width: '560px',
    backgroundColor: '#fff',
    borderRadius: '12px',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
    padding: '20px',
  },
  deleteContainor: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexDirection: 'row-reverse' as 'row-reverse',
  },
  header: {
    display: 'flex',
    borderBottom: '1px solid #e0e0e0',
    paddingBottom: '20px',
    marginBottom: '20px',
    flex: 1,
    flexDirection: 'column' as 'column',
  },
  nameContainer: {
    display: 'flex',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  userName: {
    fontSize: '1.5em',
    fontWeight: 'bold',
    margin: '0',
  },
  email: {
    color: 'gray',
    fontSize: '0.9em',
    marginTop: '4px',
  },
  infoItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px', // Space between text and icon
    fontSize: '16px',
    padding: '8px',
    justifyContent: 'space-between',
  },
  icon: {
    cursor: 'pointer',
  },
  tokenContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  tokenText: {
    fontSize: '0.95em',
    color: '#333',
  },
  button: {
    padding: '6px 12px',
    backgroundColor: '#007bff',
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
  },
  admin: {
    backgroundColor: '#ffcccb',
    color: '#b22222',
    padding: '0.2em 0.6em',
    borderRadius: '0.5em',
    fontSize: '0.9em',
    fontWeight: 'bold',
    textTransform: 'capitalize' as 'capitalize',
  },
  user: {
    backgroundColor: '#cce5ff',
    color: '#004085',
    padding: '0.2em 0.6em',
    borderRadius: '0.5em',
    fontSize: '0.9em',
    fontWeight: 'bold',
    textTransform: 'capitalize' as 'capitalize',
  },
  reader: {
    backgroundColor: '#d4edda',
    color: '#155724',
    padding: '0.2em 0.6em',
    borderRadius: '0.5em',
    fontSize: '0.9em',
    fontWeight: 'bold',
    textTransform: 'capitalize' as 'capitalize',
  },
}
